### DISCUSSION TITLE
Anyone create a device tracker in Home Assistant for ESPresense?

### DISCUSSION THREAD

**Discussion by heyitsyang** [ESPresense/ESPresense#144] [Q&A]
Just wondered if anyone has created a device tracker entity in Home Assistant for using ESPresense with the Home Assistant Companion App (as iBeacons)?

I'm about to kludge something up using device_tracker.see  & thought there might be a more elegant way already done that I missed in my searching.

**Comment by markmghali** [comment]
Also curious about this

**Reply by jrb80** [reply]
I use [MQTT device tracker](https://www.home-assistant.io/integrations/device_tracker.mqtt/), search the HA forum which has a few examples

**Reply by corgan2222** [reply]
> I use [MQTT device tracker](https://www.home-assistant.io/integrations/device_tracker.mqtt/), search the HA forum which has a few examples

how did you set up the device tracker with espresence?

**Reply by heyitsyang** [reply]
Here's my Home Assistant code.  The sensor entities ending in ble_room are what espresense populates with the room name or not_home in my situation - your sensors will be named per your mqtt_room sensor name property.  

Adding the below code will create device_trackers named by the dev_id property.   Once you have the device_trackers, you can associate them with your Persons/People as another way to determine home/not_home.  Works well for me.  I now have gps, wifi, and ble device_trackers.

```
automation:

- id: aut_update_ys_cell_ble_tracker
  alias: "aut update ys cell ble tracker"
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.ys_cell_ble_room
    - platform: homeassistant
      event: start
  action:
    - data_template:
        dev_id: ys_cell_ble
        location_name: >
          {% if states('sensor.ys_cell_ble_room') != 'not_home' -%}
            home
          {%- else -%}
            not_home
          {%- endif %}
      service: device_tracker.see

- id: aut_update_kt_cell_ble_tracker
  alias: "aut update kt cell ble tracker"
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: sensor.kt_cell_ble_room
    - platform: homeassistant
      event: start
  action:
    - data_template:
        dev_id: kt_cell_ble
        location_name: >
          {% if states('sensor.kt_cell_ble_room') != 'not_home' -%}
            home
          {%- else -%}
            not_home
          {%- endif %}
      service: device_tracker.see
```

**Reply by jrb80** [reply]
> how did you set up the device tracker with espresence?

I only have one ESP32 device so I was able to name the ESPresence room to "home" and then it was a simple matter of creating a MQTT Room Sensor and MQTT Device Tracker, example below. If you search the HA forum there  are alternate methods.

```
# configuration.yaml
device_tracker:
  - platform: mqtt
    devices:
      veryfitpro_ad_0x0af0: "homeassistant/location/veryfitpro_ad_0x0af0"
    source_type: bluetooth_le

# senors.yaml
- platform: mqtt_room
  device_id: "ad:0x0af0"
  name: 'veryfitpro_ad_0x0af0'
  state_topic: 'espresense/rooms'
  timeout: 60
  away_timeout: 120
```

**Reply by corgan2222** [reply]
> Here's my Home Assistant code. The sensor entities ending in ble_room are what espresense populates with the room name or not_home in my situation - your sensors will be named per your mqtt_room sensor name property.
> 
> Adding the below code will create device_trackers named by the dev_id property. Once you have the device_trackers, you can associate them with your Persons/People as another way to determine home/not_home. Works well for me. I now have gps, wifi, and ble device_trackers.

hmm..  @yang3535  I think this will work with only one ESPresence Device, like @jrb80 wrote. Or does this work for you with more than one device?

**Reply by heyitsyang** [reply]
It will work with as many devices as you have.  ESPresense Home Assistant sensor's default state is the name pf the room or "not_home" if not detected.  Home Assistant device trackers are expected to show either home or not_home.  The code simply changes **any rooms reported** to "home" so the device trackers work.

Just try it - it works.  I have seven ESPresense BLE detectors.

**Comment by corgan2222** [comment]
Crazy, this works.. now it makes sense.. Thanks for the tip!

![grafik](https://user-images.githubusercontent.com/12233951/146628504-69faa27b-0c38-4a81-9f38-964a98acc61c.png)

**Reply by MembershipExcel** [reply]
How did you do it ?

**Comment by bzumik1** [comment]
Hi, I am also very interested in this, is there some documentation regarding this?

**Comment by bzumik1** [comment]
I managed to implement a solution, but it would be really nice if ESPresense had a built-in device tracker. Essentially, whenever my device connects to any node, it would indicate that I am home, etc.

**Automation for Updating Device Trackers**
This automation creates and updates the state of device trackers based on the state of ESPresense sensors:
```yaml
alias: ESPresense - Convert to device_tracker
description: ""
trigger:
  - platform: state
    entity_id: 
      - sensor.jakub_iphone_espresense
      - sensor.jakub_apple_watch_espresense
      - sensor.petra_iphone_espresense
      - sensor.petra_apple_watch_espresense
condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    enabled: false
action:
  - variables:
      dev_id: "{{ trigger.to_state.entity_id.split('.')[1] }}"
      previous_state: "{{ states('device_tracker.' ~ dev_id) }}"
  - service: device_tracker.see
    data:
      dev_id: "{{ dev_id }}"
      source_type: bluetooth_le
      location_name: >-
        {% if not is_state('sensor.' ~ dev_id, 'not_home') %}
          home
        {% else %}
          not_home
        {% endif %}
mode: parallel
```
This automation will create the device trackers and update their state. If you want to modify the friendly names of the newly created device trackers, add the following to the known_devices.yaml configuration:
```yaml
jakub_iphone_espresense:
  name: Jakub - iPhone - ESPresense
  mac:
  icon: mdi:bluetooth-connect
  picture:
  track: true

jakub_apple_watch_espresense:
  name: Jakub - Apple Watch - ESPresense
  mac:
  icon: mdi:bluetooth-connect
  picture:
  track: true

petra_iphone_espresense:
  name: Petra - iPhone - ESPresense
  mac:
  icon: mdi:bluetooth-connect
  picture:
  track: true

petra_apple_watch_espresense:
  name: Petra - Apple Watch - ESPresense
  mac:
  icon: mdi:bluetooth-connect
  picture:
  track: true
```
**Request to Add Feature to ESPresense**
While this workaround is functional, it would be greatly beneficial to have this feature directly integrated into ESPresense. It would simplify the process and reduce the need for such workaround automations.

Thank you for considering this feature request!
