### DISCUSSION TITLE
iPhone & Watch not showing in Home Assistant

### DISCUSSION THREAD

**Discussion by maciekish** [ESPresense/ESPresense#1475] [General]
Hi, i have an ESP32C3 which i flashed via webui and added my iPhone and Watch to via the manual IRK method from keychain. They show up in Fingerprints of the ESP32C3 and i can see regular updates for espresense/devices/phone:maciej and espresense/devices/watch:maciej in MQTT Explorer. The ESPResence ESP32 is also listed in Home Assistant and connected. No new MQTT devices appear for the phone and watch, so i tried adding them manually as per below. Restarted HA, still nothing, no config errors.

```
sensor:
  - platform: mqtt_room
    device_id: watch:maciej
    state_topic: "espresense/devices/watch:maciej"
  - platform: mqtt_room
    device_id: phone:maciej
    state_topic: "espresense/devices/phone:maciej"
```

![image](https://github.com/user-attachments/assets/0a21604d-ffd8-4784-8c92-570dbe51d63e)
