### DISCUSSION TITLE
Beacon configuration: which state_topic in HA's sensor component?

### DISCUSSION THREAD

**Discussion by AlfredJKwack** [ESPresense/ESPresense#669] [Q&A]
Hi,

Can someone help me understand the differences in HA `sensor` configuration when it comes to beacons. Specifically I notce the notion of `state_topic` differs between sample configs of ESPresense and HA. One points to using the `espresense/devices/` while the other points to `espresense/rooms`.  Is the HA doc perhaps assuming the subject is perhaps (exlusively) oriented to devices like _base stations_ while the ESPresense one is geared towards _beacons_?

Which of the two should be used for the beacons?

The ESPresense [docs for HA](https://espresense.com/home_assistant) state that config should be something like:
```
sensor:
# One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: "iTrack:xxxxxxxxxxxx"
    name: 'ESP Keys'
    state_topic: 'espresense/devices/iTrack:xxxxxxxxxxxx'
    timeout: 10
    away_timeout: 120
```

The Home Assistant docs on [mqtt_room](https://www.home-assistant.io/integrations/mqtt_room/) state a config like below:
```
sensor:
  - platform: mqtt_room
    device_id: 123testid
    state_topic: "espresense/rooms"
```

Discussion #668 appears similar in nature though points to a specific problem the person is having.
