### ISSUE TITLE
For all iphones - lost tracking

### ISSUE THREAD

**Issue by Jens-Wymeersch** [ESPresense/ESPresense#1106]
### Describe the bug

The latest version sorted out the warning errors in Home Assistant. Now it looks like none of the iphones report their presence any more.
So my Tile and Watch still report correctly where they are, but all iphones (ios17) don't report good and indicate (not_home).

I've added the following to my configuration.yaml

```
sensor:
- platform: mqtt_room
  device_id: "irk:abc" also tried with device_id: "jens_iphone"
  name: "iPhone Jens"
  state_topic: "espresense/rooms"
  timeout: 10
  away_timeout: 120
```
and enrolled into espresence with alias iphone_jens and name iphone Jens

Finally, in all base stations, the IRK references are mentioned in the section "Known BLE identity resolving keys, should be 32 hex chars" seperated with a space.

Please advice what I need to do to regain the tracking information.

### Version

V3.3.1
