### ISSUE TITLE
ESP32 S3 Zero not working aftre firmware upload

### ISSUE THREAD

**Issue by goodm2ice** [ESPresense/ESPresense#1706]
### Describe the bug

CDC flashing not working at all (tried different standart and cdc versions). ROM Just not starting

Also tried with USB-UART CH340 and got a little more in console (in logs)

I think ESP32 S3 zero not working with Arduino framework (at least in my ESPHome working only with `esp-idf` and `wifi.output_power=8.5`).

### Version

`3.3.1`, `3.3.5`

### Firmware flavor

Standart, CDC

### Device (be specific)

ESP32 S3 Zero

### Logs

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x128
load:0x403c9700,len:0xb9c
load:0x403cc700,len:0x2878
entry 0x403c98bc
[    �Pre-Setup Free Mem: 319804
[    46][E][SPIFFS.cpp:114] format(): Formatting SPIFFS failed! Error: -1
[    47][E][SPIFFS.cpp:89] begin(): Mounting SPIFFS failed! Error: -1
Terminal disconnected: FramingError: Framing error
```

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x128
load:0x403c9700,len:0xb9c
load:0x403cc700,len:0x2878
entry 0x403c98bc
[    45][E][esp32-hal-misc.c:258] initArduino(): Failed to initialize NVS! Error: 24579
```

**Comment by ngolf** [comment]
I am having the same issue (the board is a cheap waveshare esp32 s3 zero)

Here is what else I diagnosed:
- Board & Wifi OK (uploaded a .ino script and saw connection to wifi)
- At some point I was a able to see a "configure wifi" (or something along those lines) when pressing connect, but normally I can only see Install & (Logs&Console)
- I'm also able to upload the following esphome yaml script via the esphome executable, and see a connection when connecting logs via wifi (doesn't work with cable).
```yaml
esphome:
  name: esp-test-wizard

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "ssid"
  password: "pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Test-Wizard Fallback Hotspot"
    password: "Gb0IGem8HkfA"

captive_portal:
```
