### ISSUE TITLE
2 ESPs in the same large room

### ISSUE THREAD

**Issue by jsBlackBelt** [ESPresense/ESPresense#262]
**Describe the bug**
In a big room, one ESP might not be enough.
So, what will happen if I setup 2 ESPs with the same room name and install them in 2 corners of the room?

**Comment by DeekB1983** [comment]
I think these ESP's can be picked up from quite a distance, I stay in the UK in a 3 bed semidetached house, I have 3 of these and find at times my trackers jump from one to the other even though they are spaced well far apart.

I dont see an issue with you have 2 in the same room but you need to ask yourself if it is really required.

I dont think you can have 2 with the same names though as I am sure when added to HA they will be added as different entities, like say your room name is Test-Room, you would end up with test_room_1 and test_room_2 entities and thats if the ESP Boards and mqtt can hand 2 with the same name.

If you are sure you require 2 in the same room them what you could do is have 1 at one of the room named Test-Room-1, at the other end another called Test-Room-2. You could then build a custom template sensor in yaml to combine the 2 rooms together as one and add any devices that you would require to occupy the sensor, Something like below:

```
  - sensor:    
    - name: "Test Room"
      state: >-
        {% if states("sensor.Test-Device-1") == 'Test-Room-1' %}
          Occupied
        {% elif states("sensor.Test-Device-1") == 'Test-Room-2' %}
          Occupied
        {% elif states("sensor.Test-Device-2") == 'Test-Room-1' %}
          Occupied
        {% elif states("sensor.Test-Device-2") == 'Test-Room-2' %}
          Occupied
        {% else %}
          Empty
        {% endif %}
```

But I guess this would only be for a really really large room, just an idea that may be worth trying to see if it fits your use case

**Comment by jsBlackBelt** [comment]
well, since the home assistant sensor is based on `'espresense/rooms'`:
```
sensor:
# One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: "apple:1007:11-12"
    name: 'Darrell Watch'
    state_topic: 'espresense/rooms'
    timeout: 60
    away_timeout: 120 # number of seconds after which the enitity will get status not_home
```

I guess it makes sense that 2 ESPresence NodeMCUs with the same name will publish to the same topic, so for  both NodeMCUs with the same name `someroom` - both will publish to `espresence/rooms/someroom` and by extension, if my device is close to ESP1, then it will publish and the same goes for ESP2 so regardless which ESP reports to the topic, it will recieve the message and then the HA sensor will be updated. 

I think 😅
