### ISSUE TITLE
Tractive dog collar not detected

### ISSUE THREAD

**Issue by denko81** [ESPresense/ESPresense#450]
I have a Tractive dog collar witch is not found when i search after it. The device shows up in nRF Connect. 

**Config**

- Version: 2.1.1
- Active scan enabled: Yes/No
- Include filter:
- Exclude filter:
- Query filter:

**Hardware**

- Firmware flavor:
- Device (be specific): Tractive dog collar

**Comment by DTTerastar** [comment]
Can you show info about the advertisements it sends in nRF Connect?  Screenshots?

**Comment by denko81** [comment]
![Screenshot_20220430-165952_nRF Connect](https://user-images.githubusercontent.com/26743201/166110798-cdac0e4b-2a55-443e-89c1-ad41d5c64359.jpg)

It's the device at the bottom.

**Comment by DTTerastar** [comment]
If you put f3ef8ef0acd1 into the known macs area: 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1491145/166111248-3fd14871-6c06-4e97-b24c-f16e6c9d370a.png">
and then use device id: "known:f3ef8ef0acd1" in hass mqtt_room does it work?

**Comment by denko81** [comment]
How do you mean use in hass mqtt_room?

**Comment by DTTerastar** [comment]
```
sensors:
  platform: mqtt_room
  device_id: "known:f3ef8ef0acd1"
  name: 'Dog'
  state_topic: 'espresense/rooms'
  timeout: 60
  away_timeout: 120 # number of seconds after which the enitity will get status not_home
```
