### ISSUE TITLE
Dallas DS18b20 sensor support

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense#507]
Hi, could you please add DS18b20 temperature sensor too ?

[https://esphome.io/components/sensor/dallas.html?highlight=ds18b20](url)

it works with esp8622 if that helps, and also integrated with esphome

this is its config in ESPHome in Hme assistant

```
esphome:
  name: "easttemperature"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.2.205
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "East temp"
    password: "Password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Password"

ota:
  password: "Password"
  
# Example configuration entry
dallas:
  pin: GPIO05
  update_interval: 30s

# Individual sensors
sensor:
  - platform: dallas
    address: 0xC2000004CDD71628
    name: "East temperature"
    resolution: 12
    accuracy_decimals: 2
```
