### ISSUE TITLE
binary_sensor: not allowed?

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense#511]
Getting this error:

Platform error binary_sensor.mqtt_room - No module named 'homeassistant.components.mqtt_room.binary_sensor'

of the following binary sensor:

binary_sensor:
  - platform: mqtt_room
    name: Office Mqtt Room
    sensors:
      amazfitgtr2eesp32_sticky_esp32:
        unique_id: amazfitstickyesp32
    state_topic: espresense/rooms/office/status
    json_attributes_topic: espresense/rooms/office/telemetry
    payload_on: online
    payload_off: offline
    device_class: connectivity

**Comment by DTTerastar** [comment]
I see like 2 things mashed up in your config.  mqtt_room and mqtt.binary_sensor.  Those should be totally separate entities.

**Comment by vzoltan** [comment]
Do you know how to add unique_id to binary_sensor that uses espresense sensor?

basically what id like to do is this:

have a second sensor based on my espresense sensor (device) that "turns off" delayed. to avoid little "errors" when the device is not seen, but im still home or in the room, to give it time to find it again. 


configuration.yaml:

```
binary_sensor:
  - platform: template
    scan_interval: 15
    sensors:
      amazfitgtr2epresence_sticky_esp:
        unique_id: amazfitstickyesp
        value_template: >-
          {{is_state('binary_sensor.amazfit_gtr_2e_esp', 'on')}}
        delay_off:
          minutes: 5
        friendly_name:
          Amazfit GTR 2e ON/OFF (ESP - Delayed)
```

esphome esp32 device config:

```
esp32_ble_tracker:
binary_sensor:

  - platform: ble_presence
    mac_address: E9:B5:DE:97:7B:D4
    id: amazfitgtr2e_esp
    name: "Amazfit GTR 2e (ESP)"

```
