### ISSUE TITLE
Home-Assistant configuration to show rooms with a list of devices

### ISSUE THREAD

**Issue by phrozen77** [ESPresense/ESPresense#57]
First off, let me apologize for my lack of knowledge regarding MQTT and Home-Assistant configuration in general...

So, there's example configuration to show which device is in which room (well, it provides the entity configuration for those).

Now, how would i go about listing the rooms in Home-Assistant and displaying the devices in each room?

Is that currently possible, and if so, how?

**Comment by RichieFrame** [comment]
This would be done inside HA, probably using a template sensor (per room) that reads all the MQTT room sensors, I will see if I can make one when I have time in the next few days

**Comment by corgan2222** [comment]
That's easy with this card: https://github.com/thomasloven/lovelace-auto-entities you have to install.

With this card you can filter for entity names and states:
Place a new card with this content:

```yaml
card:
  title: Devices in Office
  type: entities
filter:
  include:
    - state: office
      options:
        secondary_info: last-changed
    - name: '*espresense*'
      options:
        secondary_info: last-changed
show_empty: false
type: custom:auto-entities
```

You have to change the include filter "office" to your room name.
This should look like this:

![grafik](https://user-images.githubusercontent.com/12233951/134675116-d5fb84b7-32c6-44a2-b137-b53f0b5b6753.png)
