### ISSUE TITLE
Are MQTT room configs still necessary? 

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#680]
I setup a new ESP node today, and my BLE endpoints all grabbed the room name configured in the ESP, but I hadn't yet configured the room in HA. 

Example of a room config I have
```
mqtt:    
# MQTT Room (BLE Presence)   
   binary_sensor:
      - name: Office Room
        state_topic: espresense/rooms/office_room/status
        json_attributes_topic: espresense/rooms/office_room/telemetry
        payload_on: online
        payload_off: offline
        device_class: connectivity 
        
```
