### ISSUE TITLE
2022.12.0 release of Home Assistant doesn't want manually configured platform sensors

### ISSUE THREAD

**Issue by riddley** [ESPresense/ESPresense#725]
The documentation for ESPresense still suggests configuring it by adding them under the `sensor` platform key. Since the 2022.10.0 release of HASS, this results in a warning that your manually configured MQTT sensor(s) will stop working in the 2022.12.0 release.

I looked around for newer documentation or mention of the deprecation and didn't find it.

Is there a method that will be supported in the December release?

**Comment by hellcry37** [comment]
MQTT format changed.

under sensors:
```yaml
# ESPresense Beacons
- platform: mqtt_room
  device_id: "iTrack:xxx"
  name: 'ESP Keys Ciprian'
  state_topic: 'espresense/devices/iTrack:xxx'
  timeout: 10
  away_timeout: 120
```
under mqtt:
```yaml
binary_sensor:
  - unique_id: 'server_room'
    name: 'Server Room'
    state_topic: espresense/rooms/server_room/status
    json_attributes_topic: espresense/rooms/server_room/telemetry
    payload_on: online
    payload_off: offline
    device_class: connectivity
```
