### ISSUE TITLE
[Q] Was the "active scan" switch removed?

### ISSUE THREAD

**Issue by Nihvel** [ESPresense/ESPresense#750]
### Is your feature request related to a problem? Please describe.

I haven't used this project in a long time. I remember there used to be a switch for toggling the scanning, and the proof is at this link https://espresense.com/home_assistant where the screenshot shows Active Scan.

I recently re-flashed one of the ESP32 i used to use time ago for this same ESPresense project. This time it shows these entities in my screenshot and no switch.

![image](https://user-images.githubusercontent.com/24250443/207303251-cdf62bd4-44ca-4de4-9403-29c462290a42.png)

### Describe the solution you'd like

Highly appreciated to have the switch back. For as good as the project is, reporting is only 99% accurate, and it honestly is a waste of cpu to continuously sniff for beacons.

In Home assistant, automations can chose when to enable the scan. 

```
automation:
- id: scan when sensor detects movement
  trigger:
  - platform: state
    entity_id: binary_sensor.movement
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.espresense_active_scan
  - delay: "00:00:30"
  - service: switch.turn_off
    entity_id: switch.espresense_active_scan
```

This will allow the ESP32 to "take a break" from scanning, and will only send the message once.
Accuracy could potentially not be 100%. This depends by the position of the ESP32 and vicinity with others. But it is higher than 99% because it does not continuously listen for beacons, causing a **False Negative** to be recorded.

The grey lines are the False Negatives.

![image](https://user-images.githubusercontent.com/24250443/207306022-ea7fb8dc-2237-48a8-892d-31b0ddea51dd.png)
