### ISSUE TITLE
MQTT Device tracker

### ISSUE THREAD

**Issue by addelovein** [ESPresense/ESPresense#802]
### Is your feature request related to a problem? Please describe.

Today we add home and away using mqtt_room component which creates sensors.

Since sensors cant be associated with person object in Homeassistant a solution would be to use mqtt device tracker. 

Today we have to create an automation that first looks at the sensor and then sets the device_tracker. Kind of messy...

### Describe the solution you'd like

For us to do this properly s solution would be to have a device_tracker topic where all devices that are seen within x scope are located.

In that way we could even do a autodiscovery on device_tracker items if nedded.

### Describe alternatives you've considered

I think i got everything above

### Additional context

For Device tracker to work OTB with home assistant the following must be achieved:
<discovery_prefix>/device_tracker/[<node_id>/]<object_id>/config

So a context including device_tracker
With config with following content
'{"state_topic": "irk:c833ff332dff72d0e8c6db546cc4fd0a/state", "name": "My Tracker", "payload_home": "home", "payload_not_home": "not_home"}'

if device in a room: mosquitto_pub -h 127.0.0.1 -t irk:c833ff332dff72d0e8c6db546cc4fd0a/state -m 'home'
else
mosquitto_pub -h 127.0.0.1 -t irk:c833ff332dff72d0e8c6db546cc4fd0a/state -m 'not_home'

**Comment by micdis** [comment]
isn't the MQTT device_tracker platform, what solves this!? 

https://www.home-assistant.io/integrations/device_tracker.mqtt/

**Comment by addelovein** [comment]
Yes and no. 

"topic name format: <discovery_prefix>/device_tracker/[<node_id>/]<object_id>/config."

With this component it does not solve the problem well I can have missed something.  

Because if ESPresense loses a device and it is inactive that's when we want a device_tracker to not home.  And this we would want without an automation for each sensor from mqtt_room. 

I can't see the solution as it's setup today.

**Comment by micdis** [comment]
yes you are right - not as easy as I thought it would be! :-)

**Comment by addelovein** [comment]
From ESPresense perspective it not a challenge.  All we need is a new topic and place devices in it based on a timeout value.

**Comment by labaland** [comment]
> From ESPresense perspective it not a challenge. All we need is a new topic and place devices in it based on a timeout value. Or even better have a state home/not_home.

+1 !!!

**Comment by l-v-kuznetsov** [comment]
I second that question. Has anybody found some elegant way to create a device_tracker in HA from ESPresense?

**Comment by RaoulSargent** [comment]
I am looking at this as well and would like to link espresense to home assistant “Person”.

**Comment by ejpenney** [comment]
> I am looking at this as well and would like to link espresense to home assistant “Person”.

I personally handled this via an automation as described [here](https://github.com/ESPresense/ESPresense/discussions/144):

```
alias: "Fix: Create ESPresense Device Trackers"
description: From https://github.com/ESPresense/ESPresense/discussions/144
trigger:
  - platform: state
    id: update
    entity_id:
      - sensor.emory_s_lg_v60_bt
    from: null
    to: null
  - platform: homeassistant
    event: start
action:
  - data:
      dev_id: "{{ trigger.entity_id.replace(\"sensor.\", \"\") }}"
      location_name: >-
        {{ iif(not is_state(trigger.entity_id, "not_home"),
        "home", "not_home") }}
    service: device_tracker.see
mode: single
max_exceeded: silent
```

This is a redacted version of my automation, you can add ESPresense sensors to the trigger and it'll handle multiple sensors.  You can then add the resulting device_tracker entities to the person.

A bit hacky, but it works.  That said, I wouldn't mind a native device_tracker, even if you specify `gps/gps_accuracy` these device_trackers do NOT fire Zone triggers, which is quite frustrating.
