### ISSUE TITLE
v3.1.1 Crashes on a ESP32-WROOM-32U with external antenna.  How do I best troubleshoot?

### ISSUE THREAD

**Issue by Huwee2** [ESPresense/ESPresense#808]
### Describe the bug

Hi All,

I have a normal ESP32 running ESPresense in my driveway but recently I bought ESP32-WROOM-32U's from Aliexpress and I have fitted one of these ESP32 with an external antenna - for better coverage when I'm approaching home.

Both are ESP32's running simultaneously in the driveway with the same software v3.1.1 and same configuration (one IRK for my iPhone and filter to only report the iPhone and an ESPHome iBeacon back to MQTT)

The normal ESP32 runs successfully for days / weeks / months without problem.  The ESP32 with the external antenna crashes after 3-10 days.  My driveway gets a **lot** of passing traffic - per week: 40k cars/trucks, 6k cyclists, 4k pedestrians :-D

The last telemetry of the (crashing) ESP32-32U sent was:
```
{
   "ip":"192.168.x.x",
   "uptime":421,
   "firm":"esp32",
   "rssi":-77,
   "ver":"v3.1.1",
   "adverts":10032,
   "seen":8942,
   "reported":18,
   "freeHeap":27264,
   "maxAllocHeap":10484,
   "memFrag":61.5463615,
   "scanHighWater":1040,
   "reportHighWater":1048
}
```

Based on the troubleshooting of bug https://github.com/ESPresense/ESPresense/issues/211, I added some telemetry to HomeAssistant and we can see a crash at 10:42am:
![2023-02-22 Screenshot of ESPresense failing on ESP32-WROOM-32U](https://user-images.githubusercontent.com/97225758/220759319-38a2b898-977a-4ddc-9b5e-c152baaec187.png)

"ESPresense Driveway" is the working ESP32
"ESPresense Driveway3" is the ESP32-32U that crashes
I've added the configuration to HomeAssistant:
```
mqtt:
  sensor:
  - name: 'ESPresense Driveway Memory'      
    state_topic: espresense/rooms/driveway/telemetry
    value_template: '{{ value_json.maxAllocHeap }}'
    icon: mdi:memory
  - name: 'ESPresense Driveway3 Memory'      
    state_topic: espresense/rooms/driveway3/telemetry
    value_template: '{{ value_json.maxAllocHeap }}'
    icon: mdi:memory
```

So my question is - what's the best way to troubleshoot this while running it remotely?  Any ideas for getting logs remotely? Is there a version I can recompile and push onto the ESP32?

Thanks for your time!

### Version

v3.1.1

### Active scan enabled

No

### Include filter

None

### Exclude filter

iBeacon:xxx iPhone:xxx

### Query filter

None

### Firmware flavor

Standard

### Device (be specific)

ESP32-WROOM-32U (XX0H65)
